### PR TITLE
Update MainActivity

### PR DESCRIPTION
**Pull request by FabioGouveia**
fix : change views initialization scope

### CODE REVIEW

**Comment by shoxtrem** [comment]
Hey, @FabioGouveia  Thank you for your contribution! However, I think I didn't explain why I did it this way. My goal was to make an easy to change Java file for almost anyone to be able to change. That's he the reason I'm using all these variables. I understand memory usage is important, can't we find an alternative that preserves the original idea and improves upon memory?

**Comment by Bwaim** [comment]
I think we should have :
- A starting activity
- A template activty that is used for all the next steps of the story

Instead of using if / else for making the correspondance choice => layout. We can use a Map to have genericity. If you need help or that i detail more the explantion, tell me.

**Comment by shoxtrem** [comment]
@Bwaim  This is also my thought process. I tried to make the activities simple to edit and add. How would you change the if statements ? Can you provide some examples ? Or even submit some code version ?

**Comment by Bwaim** [comment]
Ok @shoxtrem , i will make a code version of this.

**Pull request closed without merging**
